version: '3'
services:

#Kafka Service
  kafka-1:
    image: "bitnami/kafka:3.4"
    container_name: kafka-1
    
    environment:
     - KAFKA_ENABLE_KRAFT=yes
     - ALLOW_PLAINTEXT_LISTENER=yes
     - KAFKA_CFG_NODE_ID=1001
     - KAFKA_KRAFT_CLUSTER_ID=OTMwNzFhYTY1ODNiNGE5OT

     - KAFKA_CFG_PROCESS_ROLES=broker,controller
     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT
     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1001@kafka-1:29092

     - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://localhost:9092,INTERNAL://kafka-1:19092
     - KAFKA_CFG_LISTENERS=CLIENT://:9092,CONTROLLER://kafka-1:29092,INTERNAL://:19092
     - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL

    ports:
     - "9092:9092"

  kafdrop:
    image: 'obsidiandynamics/kafdrop:3.32.0-SNAPSHOT'
    restart: "no"
    ports:
      - 9000:9000
    
    environment:
      - KAFKA_BROKERCONNECT=kafka-1:19092
      - JVM_OPTS=-Xms32M -Xmx64M
      - SERVER_SERVLET_CONTEXTPATH=/
    
    container_name: kafdrop
    depends_on:
      - "kafka-1"